
create table players(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	profile_id TEXT,
	xp INT,
	lootbox_probability INT,
	level INT,
	max_mmr INT,
	skill_mean TEXT,
	deaths INT,
	next_rank_mmr INT,
	rank INT,
	max_rank  INT,
	board_id TEXT,
	skill_stdev TEXT,
	kills INT,
	last_match_skill_stdev_change TEXT,
	update_time DATETIME,
	last_match_mmr_change INT,
	abandons TEXT,
	season INT,
	top_rank_position INT,
	last_match_skill_mean_change TEXT,
	mmr INT,
	previous_rank_mmr INT,
	last_match_result TEXT,
	wins INT,
	region TEXT,
	losses INT,
	nickname TEXT,
	platform TEXT,
	rankInfo_image TEXT,
	rankInfo_name TEXT,
	json JSON
);
